### ISSUE TITLE
PM Review: User Authentication

### ISSUE THREAD

**Issue by pedropreciado** [pedropreciado/expressr#3]

**Comment by dallashall** [comment]
@pedropreciado 
Looking good so far. Love the splash page.
Some bugs:

- [x] It doesn't redirect me anywhere after clicking Login (May be related to error below)
- [x] Input fields feel small
- [x] Getting an error when clicking 'Logout' and 'Login

Fix those, and I can probably sign off on this.

**Comment by pedropreciado** [comment]
All done. Is there anything else you recommend my fix/change before I work on my Post components??

**Comment by dallashall** [comment]
Looks good!
