### ISSUE TITLE
PA Review Follows

### ISSUE THREAD

**Issue by pedropreciado** [pedropreciado/expressr#31]

**Comment by dallashall** [comment]
This functionality works great. I wish I could click on their profiles and see a feed of their posts.

I think it would be great if you had the discover button on the top of the page.

**Comment by pedropreciado** [comment]
I’m actually working on the user show page right now! I should be finishing that up before tonight. And I’ll definitely move that button. Thanks a lot.

**Comment by pedropreciado** [comment]
The user show pages are ready. Let me know what needs to be checked!

**Comment by pedropreciado** [comment]
The user show page should be up now.

**Comment by dallashall** [comment]
Looks great!
